// SPDX-License-Identifier: BSD-3-Clause
//! Named migration inventory: each legacy case selects real native assertions.
//! Assertion names are emitted by the runner's --inventory command.
pub const Assertions = enum {
    accepted_custody,
    refused_resource_order,
    refused_serial_custody,
    failure_diagnostics,
    inadmissible_no_claim,
};
pub const Case = struct { name: []const u8, assertions: Assertions };
pub fn assertionNames(assertions: Assertions) []const u8 {
    return switch (assertions) {
        .accepted_custody => "common;mutations;privacy;accepted;custody;runCase(consume-once/retry)",
        .refused_resource_order, .failure_diagnostics => "common;mutations;privacy;refused;refusedCustody",
        .refused_serial_custody => "common;mutations;privacy;refused;serialRefusal;refusedCustody",
        .inadmissible_no_claim => "runCase(inadmissible_no_claim);privacy",
    };
}
pub const cases = [_]Case{
    .{ .name = "success", .assertions = .accepted_custody },
    .{ .name = "lowercase-grant", .assertions = .accepted_custody },
    .{ .name = "storage-azure-grant", .assertions = .accepted_custody },
    .{ .name = "cumulative-serial", .assertions = .accepted_custody },
    .{ .name = "incomplete-serial", .assertions = .accepted_custody },
    .{ .name = "stopped-boot1", .assertions = .accepted_custody },
    .{ .name = "stopped-boot2", .assertions = .accepted_custody },
    .{ .name = "stopped-both", .assertions = .accepted_custody },
    .{ .name = "cached-then-fresh", .assertions = .accepted_custody },
    .{ .name = "cumulative-cached-then-fresh", .assertions = .accepted_custody },
    .{ .name = "azure-overwritten-padding", .assertions = .accepted_custody },
    .{ .name = "azure-full-prefix", .assertions = .accepted_custody },
    .{ .name = "azure-no-advance-then-fresh", .assertions = .accepted_custody },
    .{ .name = "azure-interior-nul", .assertions = .accepted_custody },
    .{ .name = "azure-cached-then-fresh", .assertions = .accepted_custody },
    .{ .name = "bad-input", .assertions = .refused_resource_order },
    .{ .name = "preexisting-group", .assertions = .refused_resource_order },
    .{ .name = "both-grants", .assertions = .refused_resource_order },
    .{ .name = "unknown-grant", .assertions = .refused_resource_order },
    .{ .name = "duplicate-grant", .assertions = .refused_resource_order },
    .{ .name = "numeric-exponent", .assertions = .refused_resource_order },
    .{ .name = "upload-failure", .assertions = .refused_resource_order },
    .{ .name = "ambiguous-grant", .assertions = .refused_resource_order },
    .{ .name = "revoke-failure", .assertions = .refused_resource_order },
    .{ .name = "ambiguous-deploy", .assertions = .refused_resource_order },
    .{ .name = "ambiguous-deallocate", .assertions = .refused_resource_order },
    .{ .name = "ambiguous-start", .assertions = .refused_resource_order },
    .{ .name = "identity-drift", .assertions = .refused_resource_order },
    .{ .name = "attachment-mismatch", .assertions = .refused_resource_order },
    .{ .name = "serial-failure", .assertions = .refused_resource_order },
    .{ .name = "boot2-writes", .assertions = .refused_resource_order },
    .{ .name = "cleanup-unowned", .assertions = .refused_resource_order },
    .{ .name = "foreign-resource", .assertions = .refused_resource_order },
    .{ .name = "delete-failure", .assertions = .refused_resource_order },
    .{ .name = "boot1-mutated-before-start", .assertions = .refused_resource_order },
    .{ .name = "boot1-mutated-after-start", .assertions = .refused_resource_order },
    .{ .name = "boot2-admission-mutated", .assertions = .refused_resource_order },
    .{ .name = "stale-boot1-log", .assertions = .refused_serial_custody },
    .{ .name = "cumulative-prefix-drift", .assertions = .refused_resource_order },
    .{ .name = "running-reserved", .assertions = .refused_resource_order },
    .{ .name = "retained-attached", .assertions = .refused_resource_order },
    .{ .name = "final-attached", .assertions = .refused_resource_order },
    .{ .name = "retained-unattached", .assertions = .refused_resource_order },
    .{ .name = "boot1-missing-platform", .assertions = .refused_resource_order },
    .{ .name = "boot2-missing-platform", .assertions = .refused_resource_order },
    .{ .name = "stopped-bad-serial", .assertions = .refused_resource_order },
    .{ .name = "unexpected-boot1-power", .assertions = .failure_diagnostics },
    .{ .name = "unexpected-boot2-power", .assertions = .refused_resource_order },
    .{ .name = "malformed-power", .assertions = .failure_diagnostics },
    .{ .name = "retained-stopped", .assertions = .refused_resource_order },
    .{ .name = "final-stopped", .assertions = .refused_resource_order },
    .{ .name = "diagnostics-power-failure", .assertions = .failure_diagnostics },
    .{ .name = "diagnostics-read-failure", .assertions = .failure_diagnostics },
    .{ .name = "diagnostics-decode-failure", .assertions = .failure_diagnostics },
    .{ .name = "diagnostics-timeout", .assertions = .failure_diagnostics },
    .{ .name = "diagnostics-no-budget", .assertions = .failure_diagnostics },
    .{ .name = "diagnostics-unowned-group", .assertions = .failure_diagnostics },
    .{ .name = "diagnostics-foreign-resource", .assertions = .failure_diagnostics },
    .{ .name = "diagnostics-vm-identity-drift", .assertions = .failure_diagnostics },
    .{ .name = "diagnostics-disk-identity-drift", .assertions = .failure_diagnostics },
    .{ .name = "diagnostics-unknown-vm", .assertions = .failure_diagnostics },
    .{ .name = "diagnostics-delete-failure", .assertions = .failure_diagnostics },
    .{ .name = "diagnostics-read-delete-failure", .assertions = .failure_diagnostics },
    .{ .name = "different-boot1-log", .assertions = .refused_serial_custody },
    .{ .name = "cumulative-different-boot1", .assertions = .refused_serial_custody },
    .{ .name = "cache-boot1-mutated", .assertions = .refused_serial_custody },
    .{ .name = "cache-capture-mutated", .assertions = .refused_serial_custody },
    .{ .name = "cache-scope-mutated", .assertions = .refused_serial_custody },
    .{ .name = "cache-admission-mutated", .assertions = .refused_serial_custody },
    .{ .name = "cache-hash-error", .assertions = .refused_serial_custody },
    .{ .name = "cache-binding-hash-error", .assertions = .refused_serial_custody },
    .{ .name = "cache-admission-hash-error", .assertions = .refused_serial_custody },
    .{ .name = "cache-then-wrong-identity", .assertions = .refused_serial_custody },
    .{ .name = "cache-then-failure", .assertions = .refused_serial_custody },
    .{ .name = "azure-padding-only", .assertions = .refused_serial_custody },
    .{ .name = "azure-prefix-changed", .assertions = .refused_serial_custody },
    .{ .name = "azure-prefix-truncated", .assertions = .refused_serial_custody },
    .{ .name = "azure-interior-nul-removed", .assertions = .refused_serial_custody },
    .{ .name = "azure-missing-prefix", .assertions = .refused_serial_custody },
    .{ .name = "azure-wrong-boot", .assertions = .refused_serial_custody },
    .{ .name = "azure-wrong-identity", .assertions = .refused_serial_custody },
    .{ .name = "azure-writes", .assertions = .refused_serial_custody },
    .{ .name = "azure-flushes", .assertions = .refused_serial_custody },
    .{ .name = "azure-failure", .assertions = .refused_serial_custody },
    .{ .name = "azure-missing-platform", .assertions = .refused_serial_custody },
    .{ .name = "azure-all-zero-boot1", .assertions = .refused_serial_custody },
    .{ .name = "azure-incomplete-boot1", .assertions = .refused_serial_custody },
    .{ .name = "per-boot-azure-log", .assertions = .refused_serial_custody },
    .{ .name = "cumulative-azure-log", .assertions = .refused_serial_custody },
    .{ .name = "unapproved", .assertions = .inadmissible_no_claim },
    .{ .name = "expired", .assertions = .inadmissible_no_claim },
    .{ .name = "wrong-geometry", .assertions = .inadmissible_no_claim },
};
// Additional real-process coverage; not counted as legacy migration cases.
pub const process_cases = [_]Case{
    .{ .name = "process-signal-term", .assertions = .refused_resource_order },
    .{ .name = "process-output-overflow", .assertions = .refused_resource_order },
};
pub const all_cases = cases ++ process_cases;
comptime {
    if (cases.len != 92) @compileError("The frozen reference has 92 lifecycle cases");
}
