// SPDX-License-Identifier: BSD-3-Clause
const std = @import("std");
const linux = std.os.linux;
const contract = @import("build-tool-contract.zig");
const core = @import("hyperv_core");
const paths = @import("facade_paths");

pub const historical_comment =
    "/* Generated by prepare.py from matching trusted native bytes. */\n";

pub const workload_sources = [_][]const u8{
    "workloads.build.zig",
    "snapshot.zig",
    "sampler.zig",
    "native-services.zig",
    "workloads.h",
    "platform.h",
    "wasi.zig",
};

const empty_sha256 = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855";
const maximum_artifact_bytes: u64 = 512 * 1024 * 1024;
const maximum_identity_bytes = 4 * 1024 * 1024;
const operation_milliseconds = 30 * 60 * 1000;
const cleanup_milliseconds = operation_milliseconds + 30 * 1000;

pub const EmbeddedPayload = struct {
    name: []const u8,
    bytes: []const u8,
};

pub fn embeddedSourceAlloc(
    allocator: std.mem.Allocator,
    payloads: []const EmbeddedPayload,
) ![]u8 {
    var output = std.Io.Writer.Allocating.init(allocator);
    defer output.deinit();
    try output.writer.writeAll(historical_comment);
    try output.writer.writeAll("#include <stddef.h>\n");
    for (payloads) |payload| try writeEmbedded(&output.writer, payload.name, payload.bytes);
    return output.toOwnedSlice();
}

pub fn writeEmbedded(
    writer: *std.Io.Writer,
    name: []const u8,
    payload: []const u8,
) !void {
    try symbol(name);
    try writer.print("const unsigned char {s}[] = {{\n", .{name});
    var offset: usize = 0;
    while (offset < payload.len) {
        if (offset != 0) try writer.writeAll(",\n");
        const end = @min(payload.len, offset + 16);
        for (payload[offset..end], 0..) |byte, index| {
            if (index != 0) try writer.writeByte(',');
            try writer.print("0x{x:0>2}", .{byte});
        }
        offset = end;
    }
    try writer.print("\n}};\nconst size_t {s}_size = sizeof({s});\n", .{ name, name });
}

pub const Header = struct {
    revision: []const u8,
    variant: contract.Variant,
    jit_mode: ?contract.JitMode,
    source_tree_sha256: []const u8,
    compiler_sha256: []const u8,
    coremark: bool,
    wasm_sha256: []const u8,
    cwasm_sha256: []const u8,
    library_sha256: []const u8,
    coremark_wasm_sha256: ?[]const u8 = null,
    coremark_cwasm_sha256: ?[]const u8 = null,
    coremark_nofp_wasm_sha256: ?[]const u8 = null,
    coremark_nofp_cwasm_sha256: ?[]const u8 = null,
};

pub fn identityHeaderAlloc(allocator: std.mem.Allocator, header: Header) ![]u8 {
    var output = std.Io.Writer.Allocating.init(allocator);
    defer output.deinit();
    try output.writer.print(
        "#define WAMR_REVISION \"{s}\"\n" ++
            "#define WAMR_APP_VARIANT {d}\n" ++
            "#define WAMR_JIT_BOOT_MODE {d}\n" ++
            "#define WAMR_SOURCE_TREE_SHA256 \"{s}\"\n" ++
            "#define WAMR_COMPILER_SHA256 \"{s}\"\n" ++
            "#define WAMR_HAS_COREMARK {d}\n" ++
            "#define WAMR_WASM_SHA256 \"{s}\"\n" ++
            "#define WAMR_CWASM_SHA256 \"{s}\"\n" ++
            "#define WAMR_LIBRARY_SHA256 \"{s}\"\n",
        .{
            header.revision,
            @intFromEnum(header.variant),
            if (header.jit_mode) |mode| @as(u8, @intFromEnum(mode)) + 1 else 0,
            header.source_tree_sha256,
            header.compiler_sha256,
            @intFromBool(header.coremark),
            header.wasm_sha256,
            header.cwasm_sha256,
            header.library_sha256,
        },
    );
    if (header.coremark) {
        try output.writer.print(
            "#define WAMR_COREMARK_WASM_SHA256 \"{s}\"\n" ++
                "#define WAMR_COREMARK_CWASM_SHA256 \"{s}\"\n" ++
                "#define WAMR_COREMARK_NOFP_WASM_SHA256 \"{s}\"\n" ++
                "#define WAMR_COREMARK_NOFP_CWASM_SHA256 \"{s}\"\n",
            .{
                header.coremark_wasm_sha256 orelse return error.MissingCoremarkIdentity,
                header.coremark_cwasm_sha256 orelse return error.MissingCoremarkIdentity,
                header.coremark_nofp_wasm_sha256 orelse return error.MissingCoremarkIdentity,
                header.coremark_nofp_cwasm_sha256 orelse return error.MissingCoremarkIdentity,
            },
        );
    }
    return output.toOwnedSlice();
}

pub fn execute(
    allocator: std.mem.Allocator,
    io: std.Io,
    inherited: *const std.process.Environ.Map,
    arguments: contract.Arguments,
) !void {
    var repository = try contract.files.Repository.open(allocator, io, arguments.repository);
    defer repository.close(allocator, io);
    switch (arguments.command) {
        .prepare => try prepareRepository(allocator, io, inherited, repository, arguments),
        .verify => try verifyOpenRepository(allocator, io, repository),
        .olddefconfig, .native_images => return error.FoundationCommandUnavailable,
    }
}

pub fn verifyRepository(
    allocator: std.mem.Allocator,
    io: std.Io,
    repository_path: []const u8,
) !void {
    var repository = try contract.files.Repository.open(allocator, io, repository_path);
    defer repository.close(allocator, io);
    try verifyOpenRepository(allocator, io, repository);
}

pub fn variantName(variant: contract.Variant) []const u8 {
    return switch (variant) {
        .tiny => "tiny",
        .snapshot => "snapshot",
        .jit => "jit",
        .sample_aot => "sample-aot",
    };
}

pub fn jitModeName(mode: ?contract.JitMode) ?[]const u8 {
    return if (mode) |value| switch (value) {
        .fast => "fast",
        .full => "full",
    } else null;
}

const CommandRecord = struct {
    stage: Stage,
    argv: []const []const u8,
    cwd: []const u8,
};

const Stage = enum {
    zig_version,
    git_revision,
    git_archive,
    runtime_build,
    compiler_build,
    runtime_strip,
    snapshot_compute,
    snapshot_memory,
    matched_wasm,
    matched_aot,
    workload_build,
    tiny_wasm,
    tiny_aot,
    coremark_aot,
    coremark_nofp_aot,

    fn name(self: Stage) []const u8 {
        return switch (self) {
            .zig_version => "zig-version",
            .git_revision => "git-revision",
            .git_archive => "git-archive",
            .runtime_build => "runtime-build",
            .compiler_build => "compiler-build",
            .runtime_strip => "runtime-strip",
            .snapshot_compute => "snapshot-compute",
            .snapshot_memory => "snapshot-memory",
            .matched_wasm => "matched-wasm",
            .matched_aot => "matched-aot",
            .workload_build => "workload-build",
            .tiny_wasm => "tiny-wasm",
            .tiny_aot => "tiny-aot",
            .coremark_aot => "coremark-aot",
            .coremark_nofp_aot => "coremark-nofp-aot",
        };
    }
};

const Diagnostics = struct {
    directory: std.Io.Dir,
    index: usize = 0,

    fn open(io: std.Io, build: std.Io.Dir) !Diagnostics {
        const state = try contract.files.ensurePrivateDirectory(io, build, "native-environment");
        defer state.close(io);
        const diagnostics = try contract.files.ensurePrivateDirectory(io, state, "diagnostics");
        defer diagnostics.close(io);
        var name_buffer: [96]u8 = undefined;
        for (0..1000) |suffix| {
            const name = if (suffix == 0)
                try std.fmt.bufPrint(&name_buffer, "prepare-{d}", .{linux.getpid()})
            else
                try std.fmt.bufPrint(&name_buffer, "prepare-{d}-{d}", .{ linux.getpid(), suffix });
            const directory = contract.files.createPrivateDirectory(io, diagnostics, name) catch |err| switch (err) {
                error.PathAlreadyExists => continue,
                else => return err,
            };
            return .{ .directory = directory };
        }
        return error.DiagnosticDirectoryUnavailable;
    }

    fn close(self: *Diagnostics, io: std.Io) void {
        self.directory.close(io);
        self.* = undefined;
    }

    fn record(
        self: *Diagnostics,
        allocator: std.mem.Allocator,
        io: std.Io,
        stage: Stage,
        argv: []const []const u8,
        cwd: []const u8,
        result: contract.process.CommandResult,
    ) !void {
        var prefix_buffer: [96]u8 = undefined;
        const prefix = try std.fmt.bufPrint(
            &prefix_buffer,
            "{d:0>3}-{s}",
            .{ self.index, stage.name() },
        );
        self.index += 1;
        var stdout_name_buffer: [128]u8 = undefined;
        var stderr_name_buffer: [128]u8 = undefined;
        var result_name_buffer: [128]u8 = undefined;
        const stdout_name = try std.fmt.bufPrint(&stdout_name_buffer, "{s}.stdout", .{prefix});
        const stderr_name = try std.fmt.bufPrint(&stderr_name_buffer, "{s}.stderr", .{prefix});
        const result_name = try std.fmt.bufPrint(&result_name_buffer, "{s}.json", .{prefix});
        try contract.files.writePrivateCreate(io, self.directory, stdout_name, result.stdout);
        try contract.files.writePrivateCreate(io, self.directory, stderr_name, result.stderr);
        const encoded = try commandResultAlloc(allocator, stage, argv, cwd, result);
        defer allocator.free(encoded);
        try contract.files.writePrivateCreate(io, self.directory, result_name, encoded);
    }

    fn recordLaunchError(
        self: *Diagnostics,
        allocator: std.mem.Allocator,
        io: std.Io,
        stage: Stage,
        err: anyerror,
    ) !void {
        var name_buffer: [128]u8 = undefined;
        const name = try std.fmt.bufPrint(
            &name_buffer,
            "{d:0>3}-{s}.launch-error.txt",
            .{ self.index, stage.name() },
        );
        self.index += 1;
        const contents = try std.fmt.allocPrint(allocator, "{s}\n", .{@errorName(err)});
        defer allocator.free(contents);
        try contract.files.writePrivateCreate(io, self.directory, name, contents);
    }
};

const Runner = struct {
    allocator: std.mem.Allocator,
    record_allocator: std.mem.Allocator,
    io: std.Io,
    inherited: *const std.process.Environ.Map,
    build_environment: *const std.process.Environ.Map,
    primary_deadline: contract.process.Deadline,
    cleanup_deadline: contract.process.Deadline,
    diagnostics: *Diagnostics,
    commands: std.ArrayList(CommandRecord) = .empty,

    fn deinit(self: *Runner) void {
        self.commands.deinit(self.record_allocator);
    }

    fn run(
        self: *Runner,
        tool: contract.process.Tool,
        stage: Stage,
        argv: []const []const u8,
        cwd: std.Io.Dir,
        cwd_path: []const u8,
        use_build_environment: bool,
        stdout_file: ?std.Io.File,
    ) !contract.process.CommandResult {
        var recorded_argv = try self.record_allocator.alloc([]const u8, argv.len);
        for (argv, 0..) |argument, index|
            recorded_argv[index] = try self.record_allocator.dupe(u8, argument);
        try self.commands.append(self.record_allocator, .{
            .stage = stage,
            .argv = recorded_argv,
            .cwd = try self.record_allocator.dupe(u8, cwd_path),
        });
        var result = contract.process.run(self.allocator, self.io, tool, .{
            .argv = argv,
            .allow_named_argv0 = stage == .git_revision or stage == .git_archive,
            .environment = if (use_build_environment) self.build_environment else self.inherited,
            .cwd = cwd,
            .primary_deadline = self.primary_deadline,
            .cleanup_deadline = self.cleanup_deadline,
            .stdout_file = stdout_file,
            .snapshot_executable = switch (stage) {
                .zig_version,
                .git_revision,
                .git_archive,
                .runtime_build,
                .compiler_build,
                .matched_wasm,
                .workload_build,
                .tiny_wasm,
                => false,
                else => true,
            },
        }) catch |err| {
            self.diagnostics.recordLaunchError(
                self.allocator,
                self.io,
                stage,
                err,
            ) catch return error.DiagnosticWriteFailed;
            return commandFailure(stage);
        };
        errdefer result.deinit(self.allocator);
        self.diagnostics.record(
            self.allocator,
            self.io,
            stage,
            argv,
            cwd_path,
            result,
        ) catch return error.DiagnosticWriteFailed;
        if (!result.succeeded()) return commandFailure(stage);
        return result;
    }
};

fn prepareRepository(
    allocator: std.mem.Allocator,
    io: std.Io,
    inherited: *const std.process.Environ.Map,
    repository: contract.files.Repository,
    arguments: contract.Arguments,
) !void {
    const previous_umask = linux.syscall1(.umask, 0o077);
    defer _ = linux.syscall1(.umask, previous_umask);
    var arena = std.heap.ArenaAllocator.init(allocator);
    defer arena.deinit();
    const a = arena.allocator();
    const build_path = try std.fs.path.join(a, &.{ repository.app.path, "build" });
    const artifacts_path = try std.fs.path.join(a, &.{ build_path, "artifacts" });
    const work_path = try std.fs.path.join(a, &.{ build_path, "wamr-source" });
    const archive_path = try std.fs.path.join(a, &.{ build_path, "wamr-source.tar" });
    const consumer_path = try std.fs.path.join(a, &.{ build_path, "workload-consumer" });
    const scratch_path = try std.fs.path.join(a, &.{ build_path, "scratch" });

    const build = try contract.files.ensurePrivateDirectory(io, repository.app.dir, "build");
    defer build.close(io);
    var diagnostics = try Diagnostics.open(io, build);
    defer diagnostics.close(io);

    var build_environment = try cloneEnvironment(allocator, inherited);
    defer build_environment.deinit();
    try configureBuildEnvironment(allocator, io, build, build_path, scratch_path, &build_environment);

    var runner: Runner = .{
        .allocator = allocator,
        .record_allocator = a,
        .io = io,
        .inherited = inherited,
        .build_environment = &build_environment,
        .primary_deadline = try contract.process.Deadline.afterMilliseconds(operation_milliseconds),
        .cleanup_deadline = try contract.process.Deadline.afterMilliseconds(cleanup_milliseconds),
        .diagnostics = &diagnostics,
    };
    defer runner.deinit();

    var zig = try contract.process.resolveTool(allocator, io, inherited, "zig");
    defer zig.close(allocator, io);
    var objcopy = try contract.process.resolveTool(allocator, io, inherited, "llvm-objcopy");
    defer objcopy.close(allocator, io);
    try configureZigLibrary(allocator, io, zig.path, &build_environment);
    {
        var version = try runner.run(
            zig,
            .zig_version,
            &.{ zig.path, "version" },
            repository.app.dir,
            repository.app.path,
            false,
            null,
        );
        defer version.deinit(allocator);
        if (!std.mem.eql(u8, std.mem.trim(u8, version.stdout, " \t\r\n"), contract.zig_version))
            return error.UnsupportedZigVersion;
    }

    const revision = arguments.development_revision orelse
        if (arguments.variant == .tiny) contract.revision else contract.workload_revision;
    try contract.validateRevision(revision);

    var source_directory: ?contract.files.SourceDirectory = null;
    defer if (source_directory) |directory| directory.close(allocator, io);
    var selected_archive: ?contract.files.RetainedFile = null;
    defer if (selected_archive) |*archive| archive.close(io);
    var git: ?contract.process.Tool = null;
    defer if (git) |*tool| tool.close(allocator, io);

    if (arguments.source) |source_path| {
        if (paths.isSameOrAncestor(build_path, source_path) or
            paths.isSameOrAncestor(source_path, build_path))
            return error.SourceOutputAlias;
        source_directory = try contract.files.SourceDirectory.open(allocator, io, source_path);
        git = try contract.process.resolveTool(allocator, io, inherited, "git");
        const revision_spec = try std.fmt.allocPrint(a, "{s}^{{commit}}", .{revision});
        var result = try runner.run(
            git.?,
            .git_revision,
            &.{ "git", "rev-parse", revision_spec },
            source_directory.?.dir,
            source_directory.?.path,
            false,
            null,
        );
        defer result.deinit(allocator);
        if (!std.mem.eql(u8, std.mem.trim(u8, result.stdout, " \t\r\n"), revision))
            return error.SourceRevisionUnavailable;
    } else if (arguments.source_archive) |selected| {
        if (paths.isSameOrAncestor(build_path, selected) or
            paths.isSameOrAncestor(selected, build_path))
            return error.SourceOutputAlias;
        if (!std.mem.eql(u8, revision, contract.revision))
            return error.UnsupportedCombination;
        selected_archive = try contract.files.RetainedFile.open(io, selected, .artifact);
    } else {
        unreachable;
    }

    const artifacts = try contract.files.createPrivateDirectory(io, build, "artifacts");
    defer artifacts.close(io);

    var created_archive = false;
    const selected_archive_path = if (source_directory != null) archive_path else arguments.source_archive.?;
    if (source_directory != null) {
        const archive = try build.createFile(io, "wamr-source.tar", .{
            .exclusive = true,
            .permissions = .fromMode(0o600),
        });
        defer archive.close(io);
        try archive.setPermissions(io, .fromMode(0o600));
        var result = try runner.run(
            git.?,
            .git_archive,
            &.{ "git", "archive", revision },
            source_directory.?.dir,
            source_directory.?.path,
            false,
            archive,
        );
        defer result.deinit(allocator);
        try archive.sync(io);
        try requireFile(io, archive, 0o600, null);
        created_archive = true;
    }

    _ = try contract.files.extractGitArchive(
        allocator,
        io,
        selected_archive_path,
        work_path,
        .{},
    );
    if (source_directory) |selected| {
        const reopened = try contract.files.SourceDirectory.open(allocator, io, selected.path);
        defer reopened.close(allocator, io);
        try requireSourceDirectoryIdentity(selected, reopened);
    }
    if (selected_archive) |archive| try archive.verify(io);
    if (created_archive) {
        try build.deleteFile(io, "wamr-source.tar");
        try syncDirectory(io, build);
    }

    var source_identity = try contract.files.sourceIdentity(allocator, io, work_path, .{});
    defer source_identity.deinit(allocator);
    try contract.files.writePrivateCreate(io, build, "source-files.json", source_identity.bytes);

    const work = try contract.files.SourceDirectory.open(allocator, io, work_path);
    defer work.close(allocator, io);
    try buildRuntimeAndCompiler(a, allocator, io, repository, work, build_path, &runner, zig, artifacts);
    try buildWorkload(
        a,
        allocator,
        io,
        repository,
        work,
        build_path,
        artifacts_path,
        consumer_path,
        arguments.variant,
        arguments.coremark,
        &runner,
        zig,
        objcopy,
        artifacts,
    );
    try buildTinyAndCoremark(
        a,
        allocator,
        io,
        repository,
        work,
        artifacts_path,
        arguments.coremark,
        &runner,
        zig,
        artifacts,
    );

    try writeGeneratedContracts(
        a,
        allocator,
        io,
        repository,
        artifacts,
        artifacts_path,
        arguments,
        revision,
        source_identity.sha256[0..],
    );

    const identity_bytes = try identityManifestAlloc(
        a,
        allocator,
        io,
        repository,
        artifacts,
        artifacts_path,
        arguments,
        revision,
        source_identity.sha256[0..],
        runner.commands.items,
        zig.path,
        objcopy.path,
    );
    defer allocator.free(identity_bytes);
    try contract.files.writePrivateCreate(
        io,
        diagnostics.directory,
        "candidate-identity.json",
        identity_bytes,
    );
    verifyIdentityBytes(allocator, io, repository, identity_bytes, false) catch |err| {
        try contract.files.writePrivateCreate(
            io,
            diagnostics.directory,
            "verification-error.txt",
            @errorName(err),
        );
        return err;
    };
    try contract.files.writePrivateAtomicCreate(io, artifacts, "identity.json", identity_bytes);
    try verifyOpenRepository(allocator, io, repository);
}

fn buildRuntimeAndCompiler(
    a: std.mem.Allocator,
    allocator: std.mem.Allocator,
    io: std.Io,
    repository: contract.files.Repository,
    work: contract.files.SourceDirectory,
    build_path: []const u8,
    runner: *Runner,
    zig: contract.process.Tool,
    artifacts: std.Io.Dir,
) !void {
    const runtime_prefix = try std.fs.path.join(a, &.{ build_path, "runtime" });
    const host_prefix = try std.fs.path.join(a, &.{ build_path, "host" });
    {
        var result = try runner.run(
            zig,
            .runtime_build,
            &.{
                zig.path,
                "build",
                "-Dprofile=unikraft-aot",
                "-Doptimize=ReleaseSafe",
                "--prefix",
                runtime_prefix,
                "-j2",
            },
            work.dir,
            work.path,
            true,
            null,
        );
        defer result.deinit(allocator);
    }
    {
        var result = try runner.run(
            zig,
            .compiler_build,
            &.{
                zig.path,
                "build",
                "native-aot-fixture",
                "-Doptimize=ReleaseSafe",
                "-Dstrip=true",
                "--prefix",
                host_prefix,
                "-j2",
            },
            work.dir,
            work.path,
            true,
            null,
        );
        defer result.deinit(allocator);
    }
    try copySourceFile(io, work, "include/wamr_aot.h", artifacts, "wamr_aot.h", 0o600);
    const wamrc = try std.fs.path.join(a, &.{ host_prefix, "bin", "wamrc" });
    try copyAbsoluteFile(allocator, io, wamrc, artifacts, "wamrc", 0o700);
    _ = repository;
}

fn buildWorkload(
    a: std.mem.Allocator,
    allocator: std.mem.Allocator,
    io: std.Io,
    repository: contract.files.Repository,
    work: contract.files.SourceDirectory,
    build_path: []const u8,
    artifacts_path: []const u8,
    consumer_path: []const u8,
    variant: contract.Variant,
    coremark: bool,
    runner: *Runner,
    zig: contract.process.Tool,
    objcopy: contract.process.Tool,
    artifacts: std.Io.Dir,
) !void {
    const build = try contract.files.PrivateDirectory.open(io, build_path);
    defer build.close(io);
    const consumer = try contract.files.createPrivateDirectory(io, build.dir, "workload-consumer");
    defer consumer.close(io);
    for (workload_sources) |name| try copySourceFile(
        io,
        repository.app,
        name,
        consumer,
        if (std.mem.eql(u8, name, "workloads.build.zig")) "build.zig" else name,
        0o600,
    );
    try contract.files.writePrivateCreate(
        io,
        consumer,
        "build.zig.zon",
        ".{ .name = .wamr_workload_image, .version = \"0.0.0\", " ++
            ".fingerprint = 0xcb36ebabb0542062, " ++
            ".dependencies = .{ .wamr = .{ .path = \"../wamr-source\" } }, " ++
            ".paths = .{ \".\" } }\n",
    );

    var artifacts_source = std.Io.Writer.Allocating.init(allocator);
    defer artifacts_source.deinit();
    switch (variant) {
        .tiny => {},
        .snapshot => {
            inline for (.{
                .{ "compute", "unroll4" },
                .{ "memory", "iv_store" },
            }) |item| {
                const wasm_name = item[0] ++ ".wasm";
                const cwasm_name = item[0] ++ ".cwasm";
                const source_name = "tests/benchmarks/loop-passes/" ++ item[1] ++ ".wasm";
                try copySourceFile(io, work, source_name, artifacts, wasm_name, 0o600);
                try compileAot(
                    a,
                    allocator,
                    io,
                    repository,
                    artifacts_path,
                    wasm_name,
                    cwasm_name,
                    if (std.mem.eql(u8, item[0], "compute")) .snapshot_compute else .snapshot_memory,
                    runner,
                );
                try copyAbsoluteFile(
                    allocator,
                    io,
                    try std.fs.path.join(a, &.{ artifacts_path, wasm_name }),
                    consumer,
                    wasm_name,
                    0o600,
                );
                try copyAbsoluteFile(
                    allocator,
                    io,
                    try std.fs.path.join(a, &.{ artifacts_path, cwasm_name }),
                    consumer,
                    cwasm_name,
                    0o600,
                );
                try artifacts_source.writer.print(
                    "pub const {s}_wasm = @embedFile(\"{s}\");\n" ++
                        "pub const {s}_aot = @embedFile(\"{s}\");\n",
                    .{ item[0], wasm_name, item[0], cwasm_name },
                );
            }
        },
        .jit, .sample_aot => {
            const matched_wasm = try std.fs.path.join(a, &.{ artifacts_path, "matched.wasm" });
            const fixture = try std.fs.path.join(a, &.{
                work.path,
                "tests",
                "unikraft-jit",
                "fixture.zig",
            });
            {
                const emit = try std.fmt.allocPrint(a, "-femit-bin={s}", .{matched_wasm});
                var result = try runner.run(
                    zig,
                    .matched_wasm,
                    &.{
                        zig.path,
                        "build-exe",
                        fixture,
                        "-target",
                        "wasm32-freestanding",
                        "-O",
                        "ReleaseSmall",
                        "-fno-entry",
                        "-rdynamic",
                        "--stack",
                        "16384",
                        "--initial-memory=131072",
                        "--max-memory=524288",
                        emit,
                    },
                    repository.app.dir,
                    repository.app.path,
                    true,
                    null,
                );
                defer result.deinit(allocator);
                try setAbsoluteMode(io, matched_wasm, 0o700);
            }
            try compileAot(
                a,
                allocator,
                io,
                repository,
                artifacts_path,
                "matched.wasm",
                "matched.cwasm",
                .matched_aot,
                runner,
            );
            try copyAbsoluteFile(
                allocator,
                io,
                try std.fs.path.join(a, &.{ artifacts_path, "matched.cwasm" }),
                consumer,
                "matched.cwasm",
                0o600,
            );
            try artifacts_source.writer.print(
                "pub const with_compiler = {s};\n" ++
                    "pub const aot = @embedFile(\"matched.cwasm\");\n",
                .{if (variant == .jit) "true" else "false"},
            );
        },
    }
    const generated = try artifacts_source.toOwnedSlice();
    defer allocator.free(generated);
    try contract.files.writePrivateCreate(io, consumer, "artifacts.zig", generated);

    const output = try std.fs.path.join(a, &.{ consumer_path, "out" });
    const variant_option = try std.fmt.allocPrint(a, "-Dvariant={s}", .{variantName(variant)});
    const coremark_option = try std.fmt.allocPrint(
        a,
        "-Dcoremark={s}",
        .{if (coremark) "true" else "false"},
    );
    {
        var consumer_source = try contract.files.SourceDirectory.open(allocator, io, consumer_path);
        defer consumer_source.close(allocator, io);
        var result = try runner.run(
            zig,
            .workload_build,
            &.{
                zig.path,
                "build",
                variant_option,
                coremark_option,
                "-j2",
                "--prefix",
                output,
            },
            consumer_source.dir,
            consumer_source.path,
            true,
            null,
        );
        defer result.deinit(allocator);
    }
    if (variant == .jit or variant == .sample_aot) {
        const installed = try std.fs.path.join(a, &.{ output, "matched.wasm" });
        const selected = try std.fs.path.join(a, &.{ artifacts_path, "matched.wasm" });
        if (!std.mem.eql(
            u8,
            &(try digestAbsolute(io, installed, maximum_artifact_bytes)),
            &(try digestAbsolute(io, selected, maximum_artifact_bytes)),
        )) return error.MatchedWorkloadMismatch;
    }
    const library = try std.fs.path.join(a, &.{ output, "lib", "libwamr-aot.a" });
    const stripped = try std.fs.path.join(
        a,
        &.{ build_path, "scratch", "libwamr-aot.stripped.a" },
    );
    {
        var result = try runner.run(
            objcopy,
            .runtime_strip,
            &.{ objcopy.path, "--strip-debug", library, stripped },
            work.dir,
            work.path,
            true,
            null,
        );
        defer result.deinit(allocator);
    }
    try copyAbsoluteFile(
        allocator,
        io,
        stripped,
        artifacts,
        "libwamr-aot.a",
        0o600,
    );
}

fn buildTinyAndCoremark(
    a: std.mem.Allocator,
    allocator: std.mem.Allocator,
    io: std.Io,
    repository: contract.files.Repository,
    work: contract.files.SourceDirectory,
    artifacts_path: []const u8,
    coremark: bool,
    runner: *Runner,
    zig: contract.process.Tool,
    artifacts: std.Io.Dir,
) !void {
    const tiny_wasm = try std.fs.path.join(a, &.{ artifacts_path, "tiny.wasm" });
    const fixture = try std.fs.path.join(a, &.{ repository.app.path, "fixture.zig" });
    {
        const emit = try std.fmt.allocPrint(a, "-femit-bin={s}", .{tiny_wasm});
        var result = try runner.run(
            zig,
            .tiny_wasm,
            &.{
                zig.path,
                "build-exe",
                fixture,
                "-target",
                "wasm32-freestanding",
                "-O",
                "ReleaseSmall",
                "-fno-entry",
                "-rdynamic",
                "--stack",
                "16384",
                "--initial-memory=131072",
                "--max-memory=524288",
                emit,
            },
            repository.app.dir,
            repository.app.path,
            true,
            null,
        );
        defer result.deinit(allocator);
        try setAbsoluteMode(io, tiny_wasm, 0o700);
    }
    try compileAot(
        a,
        allocator,
        io,
        repository,
        artifacts_path,
        "tiny.wasm",
        "tiny.cwasm",
        .tiny_aot,
        runner,
    );
    if (coremark) {
        inline for (.{
            .{ "coremark", "coremark_wasi.wasm", Stage.coremark_aot },
            .{ "coremark-nofp", "coremark_wasi_nofp.wasm", Stage.coremark_nofp_aot },
        }) |item| {
            const wasm_name = item[0] ++ ".wasm";
            const cwasm_name = item[0] ++ ".cwasm";
            const source_name = "tests/benchmarks/coremark/" ++ item[1];
            try copySourceFile(io, work, source_name, artifacts, wasm_name, 0o600);
            try compileAot(
                a,
                allocator,
                io,
                repository,
                artifacts_path,
                wasm_name,
                cwasm_name,
                item[2],
                runner,
            );
        }
    }
}

fn compileAot(
    a: std.mem.Allocator,
    allocator: std.mem.Allocator,
    io: std.Io,
    repository: contract.files.Repository,
    artifacts_path: []const u8,
    input_name: []const u8,
    output_name: []const u8,
    stage: Stage,
    runner: *Runner,
) !void {
    const compiler_path = try std.fs.path.join(a, &.{ artifacts_path, "wamrc" });
    var compiler = try contract.process.openTool(allocator, io, "wamrc", compiler_path);
    defer compiler.close(allocator, io);
    const input = try std.fs.path.join(a, &.{ artifacts_path, input_name });
    const output = try std.fs.path.join(a, &.{ artifacts_path, output_name });
    const profile = try std.fmt.allocPrint(a, "--profile={s}", .{contract.compiler_profile});
    var result = try runner.run(
        compiler,
        stage,
        &.{
            compiler.path,
            "compile",
            "--target=x86_64",
            profile,
            input,
            "-o",
            output,
        },
        repository.app.dir,
        repository.app.path,
        true,
        null,
    );
    defer result.deinit(allocator);
    try setAbsoluteMode(io, output, 0o600);
}

fn writeGeneratedContracts(
    a: std.mem.Allocator,
    allocator: std.mem.Allocator,
    io: std.Io,
    repository: contract.files.Repository,
    artifacts: std.Io.Dir,
    artifacts_path: []const u8,
    arguments: contract.Arguments,
    revision: []const u8,
    source_tree_sha256: []const u8,
) !void {
    const tiny = try readAbsolute(
        allocator,
        io,
        try std.fs.path.join(a, &.{ artifacts_path, "tiny.cwasm" }),
        maximum_artifact_bytes,
    );
    defer allocator.free(tiny);
    var coremark_bytes: ?[]u8 = null;
    defer if (coremark_bytes) |bytes| allocator.free(bytes);
    var coremark_nofp_bytes: ?[]u8 = null;
    defer if (coremark_nofp_bytes) |bytes| allocator.free(bytes);
    var payloads: [3]EmbeddedPayload = undefined;
    var payload_count: usize = 1;
    payloads[0] = .{ .name = "wamr_fixture", .bytes = tiny };
    if (arguments.coremark) {
        coremark_bytes = try readAbsolute(
            allocator,
            io,
            try std.fs.path.join(a, &.{ artifacts_path, "coremark.cwasm" }),
            maximum_artifact_bytes,
        );
        coremark_nofp_bytes = try readAbsolute(
            allocator,
            io,
            try std.fs.path.join(a, &.{ artifacts_path, "coremark-nofp.cwasm" }),
            maximum_artifact_bytes,
        );
        payloads[1] = .{ .name = "wamr_coremark", .bytes = coremark_bytes.? };
        payloads[2] = .{ .name = "wamr_coremark_nofp", .bytes = coremark_nofp_bytes.? };
        payload_count = 3;
    }
    const embedded = try embeddedSourceAlloc(allocator, payloads[0..payload_count]);
    defer allocator.free(embedded);
    try contract.files.writePrivateCreate(io, artifacts, "embedded.c", embedded);

    const header = try identityHeaderAlloc(allocator, .{
        .revision = revision,
        .variant = arguments.variant,
        .jit_mode = arguments.jit_mode,
        .source_tree_sha256 = source_tree_sha256,
        .compiler_sha256 = &(try artifactDigest(io, artifacts_path, "wamrc", 0o700)),
        .coremark = arguments.coremark,
        .wasm_sha256 = &(try artifactDigest(io, artifacts_path, "tiny.wasm", 0o700)),
        .cwasm_sha256 = &(try artifactDigest(io, artifacts_path, "tiny.cwasm", 0o600)),
        .library_sha256 = &(try artifactDigest(io, artifacts_path, "libwamr-aot.a", 0o600)),
        .coremark_wasm_sha256 = if (arguments.coremark)
            &(try artifactDigest(io, artifacts_path, "coremark.wasm", 0o600))
        else
            null,
        .coremark_cwasm_sha256 = if (arguments.coremark)
            &(try artifactDigest(io, artifacts_path, "coremark.cwasm", 0o600))
        else
            null,
        .coremark_nofp_wasm_sha256 = if (arguments.coremark)
            &(try artifactDigest(io, artifacts_path, "coremark-nofp.wasm", 0o600))
        else
            null,
        .coremark_nofp_cwasm_sha256 = if (arguments.coremark)
            &(try artifactDigest(io, artifacts_path, "coremark-nofp.cwasm", 0o600))
        else
            null,
    });
    defer allocator.free(header);
    try contract.files.writePrivateCreate(io, artifacts, "identity.h", header);
    _ = repository;
}

const ArtifactIdentity = struct {
    name: []const u8,
    sha256: [64]u8,

    fn less(_: void, left: ArtifactIdentity, right: ArtifactIdentity) bool {
        return std.mem.lessThan(u8, left.name, right.name);
    }
};

fn identityManifestAlloc(
    a: std.mem.Allocator,
    allocator: std.mem.Allocator,
    io: std.Io,
    repository: contract.files.Repository,
    artifacts: std.Io.Dir,
    artifacts_path: []const u8,
    arguments: contract.Arguments,
    revision: []const u8,
    source_tree_sha256: []const u8,
    commands: []const CommandRecord,
    zig_path: []const u8,
    objcopy_path: []const u8,
) ![]u8 {
    var artifact_identities: std.ArrayList(ArtifactIdentity) = .empty;
    defer artifact_identities.deinit(allocator);
    for (try expectedArtifacts(a, arguments.variant, arguments.coremark)) |expected| {
        try artifact_identities.append(allocator, .{
            .name = expected.name,
            .sha256 = try artifactDigest(io, artifacts_path, expected.name, expected.mode),
        });
    }
    std.mem.sort(ArtifactIdentity, artifact_identities.items, {}, ArtifactIdentity.less);

    const fixture_sha256 = try trackedDigest(
        allocator,
        io,
        repository.app,
        "fixture.zig",
    );
    const prepare_sha256 = try trackedDigest(
        allocator,
        io,
        repository.app,
        "build-tool-prepare.zig",
    );
    var workload_identities: [workload_sources.len][64]u8 = undefined;
    for (workload_sources, 0..) |name, index|
        workload_identities[index] = try trackedDigest(
            allocator,
            io,
            repository.app,
            name,
        );
    const wasi_sha256 = if (arguments.coremark)
        try trackedDigest(
            allocator,
            io,
            repository.app,
            "wasi.zig",
        )
    else
        null;

    var raw = std.Io.Writer.Allocating.init(allocator);
    defer raw.deinit();
    try raw.writer.writeByte('{');
    try jsonFieldName(&raw.writer, "schema_version", false);
    try raw.writer.writeAll("1");
    try jsonFieldName(&raw.writer, "scope", true);
    try contract.json.writeString(
        &raw.writer,
        if (arguments.development_revision != null)
            contract.development_scope
        else
            contract.supported_scope,
    );
    try jsonFieldName(&raw.writer, "development_only", true);
    try raw.writer.writeAll(if (arguments.development_revision != null) "true" else "false");
    try jsonFieldName(&raw.writer, "variant", true);
    try contract.json.writeString(&raw.writer, variantName(arguments.variant));
    try jsonFieldName(&raw.writer, "jit_mode", true);
    if (jitModeName(arguments.jit_mode)) |mode|
        try contract.json.writeString(&raw.writer, mode)
    else
        try raw.writer.writeAll("null");
    try jsonFieldName(&raw.writer, "wamr_revision", true);
    try contract.json.writeString(&raw.writer, revision);
    try jsonFieldName(&raw.writer, "source_tree_sha256", true);
    try contract.json.writeString(&raw.writer, source_tree_sha256);
    try jsonFieldName(&raw.writer, "source_identity_recipe", true);
    try contract.json.writeString(&raw.writer, contract.source_identity_recipe);
    try jsonFieldName(&raw.writer, "source_tracked_diff_sha256", true);
    try contract.json.writeString(&raw.writer, empty_sha256);
    try jsonFieldName(&raw.writer, "compiler_profile", true);
    try contract.json.writeString(&raw.writer, contract.compiler_profile);
    try jsonFieldName(&raw.writer, "zig_version", true);
    try contract.json.writeString(&raw.writer, contract.zig_version);
    try jsonFieldName(&raw.writer, "runtime_options", true);
    try writeStringArray(&raw.writer, &contract.native_flags);
    try jsonFieldName(&raw.writer, "compiler_runtime_provider", true);
    try contract.json.writeString(&raw.writer, contract.compiler_runtime_provider);
    try jsonFieldName(&raw.writer, "commands", true);
    try writeCommands(a, &raw.writer, commands, repository.app.path, zig_path, objcopy_path);
    try jsonFieldName(&raw.writer, "compiler_options", true);
    try writeStringArray(&raw.writer, &.{ "optimize=ReleaseSafe", "strip=true" });
    try jsonFieldName(&raw.writer, "minimal_wasi", true);
    try raw.writer.writeAll(if (arguments.coremark) "true" else "false");
    try jsonFieldName(&raw.writer, "wasi_bridge_sha256", true);
    if (wasi_sha256) |sha|
        try contract.json.writeString(&raw.writer, &sha)
    else
        try raw.writer.writeAll("null");
    try jsonFieldName(&raw.writer, "fixture_source_sha256", true);
    try contract.json.writeString(&raw.writer, &fixture_sha256);
    try jsonFieldName(&raw.writer, "prepare_source_sha256", true);
    try contract.json.writeString(&raw.writer, &prepare_sha256);
    try jsonFieldName(&raw.writer, "workload_sources", true);
    try raw.writer.writeByte('{');
    for (workload_sources, 0..) |name, index| {
        if (index != 0) try raw.writer.writeByte(',');
        try contract.json.writeString(&raw.writer, name);
        try raw.writer.writeByte(':');
        try contract.json.writeString(&raw.writer, &workload_identities[index]);
    }
    try raw.writer.writeByte('}');
    try jsonFieldName(&raw.writer, "files", true);
    try raw.writer.writeByte('{');
    for (artifact_identities.items, 0..) |artifact, index| {
        if (index != 0) try raw.writer.writeByte(',');
        try contract.json.writeString(&raw.writer, artifact.name);
        try raw.writer.writeByte(':');
        try contract.json.writeString(&raw.writer, &artifact.sha256);
    }
    try raw.writer.writeAll("}");
    try raw.writer.writeByte('}');
    const compact = try raw.toOwnedSlice();
    defer allocator.free(compact);
    var document = try contract.json.parse(allocator, compact, .{
        .bytes = maximum_identity_bytes,
        .depth = 32,
        .string_bytes = 64 * 1024,
        .items = 4096,
        .tokens = 65536,
    });
    defer document.deinit();
    _ = artifacts;
    return contract.json.valueAlloc(allocator, document.value(), .pretty);
}

fn verifyOpenRepository(
    allocator: std.mem.Allocator,
    io: std.Io,
    repository: contract.files.Repository,
) !void {
    const identity_path = try std.fs.path.join(
        allocator,
        &.{ repository.app.path, "build", "artifacts", "identity.json" },
    );
    defer allocator.free(identity_path);
    var identity = try contract.files.RetainedFile.open(io, identity_path, .private);
    defer identity.close(io);
    const before = identity.file_snapshot;
    if (before.size == 0 or before.size > maximum_identity_bytes)
        return error.InvalidIdentity;
    const bytes = try allocator.alloc(u8, @intCast(before.size));
    defer allocator.free(bytes);
    if (try identity.file.readPositionalAll(io, bytes, 0) != bytes.len)
        return error.IdentityChanged;
    try identity.verify(io);
    try verifyIdentityBytes(allocator, io, repository, bytes, true);
    try identity.verify(io);
}

const IdentityView = struct {
    fields: std.json.ObjectMap,
    variant: contract.Variant,
    jit_mode: ?contract.JitMode,
    coremark: bool,
    development: bool,
    revision: []const u8,
    source_tree_sha256: []const u8,
    files: std.json.ObjectMap,
    commands: std.json.Array,
};

fn verifyIdentityBytes(
    allocator: std.mem.Allocator,
    io: std.Io,
    repository: contract.files.Repository,
    bytes: []const u8,
    published: bool,
) !void {
    var document = try contract.json.parse(allocator, bytes, .{
        .bytes = maximum_identity_bytes,
        .depth = 32,
        .string_bytes = 64 * 1024,
        .items = 4096,
        .tokens = 65536,
    });
    defer document.deinit();
    const identity = try parseIdentity(document.value());
    const expected_revision = if (identity.variant == .tiny)
        contract.revision
    else
        contract.workload_revision;
    if ((!identity.development and
        !std.mem.eql(u8, identity.revision, expected_revision)) or
        (identity.development and
            !std.mem.eql(
                u8,
                try stringField(identity.fields, "scope"),
                contract.development_scope,
            )))
        return error.UnsupportedProducerIdentity;
    if (!identity.development and !std.mem.eql(
        u8,
        try stringField(identity.fields, "scope"),
        contract.supported_scope,
    )) return error.UnsupportedProducerIdentity;
    try contract.validateRevision(identity.revision);
    if (!std.mem.eql(u8, try stringField(identity.fields, "compiler_profile"), contract.compiler_profile) or
        !std.mem.eql(u8, try stringField(identity.fields, "zig_version"), contract.zig_version) or
        !std.mem.eql(
            u8,
            try stringField(identity.fields, "source_identity_recipe"),
            contract.source_identity_recipe,
        ) or
        !std.mem.eql(
            u8,
            try stringField(identity.fields, "source_tracked_diff_sha256"),
            empty_sha256,
        ) or
        !std.mem.eql(
            u8,
            try stringField(identity.fields, "compiler_runtime_provider"),
            contract.compiler_runtime_provider,
        ))
        return error.UnsupportedProducerIdentity;
    try expectStringArray(identity.fields.get("runtime_options").?, &contract.native_flags);
    try expectStringArray(identity.fields.get("compiler_options").?, &.{ "optimize=ReleaseSafe", "strip=true" });

    const build_path = try std.fs.path.join(allocator, &.{ repository.app.path, "build" });
    defer allocator.free(build_path);
    const artifacts_path = try std.fs.path.join(allocator, &.{ build_path, "artifacts" });
    defer allocator.free(artifacts_path);
    const work_path = try std.fs.path.join(allocator, &.{ build_path, "wamr-source" });
    defer allocator.free(work_path);
    const source_files_path = try std.fs.path.join(allocator, &.{ build_path, "source-files.json" });
    defer allocator.free(source_files_path);

    var source_identity = try contract.files.sourceIdentity(allocator, io, work_path, .{});
    defer source_identity.deinit(allocator);
    var source_files = try contract.files.RetainedFile.open(io, source_files_path, .private);
    defer source_files.close(io);
    if (source_files.file_snapshot.size == 0 or
        source_files.file_snapshot.size > maximum_identity_bytes)
        return error.SourceIdentityMismatch;
    const source_bytes = try allocator.alloc(u8, @intCast(source_files.file_snapshot.size));
    defer allocator.free(source_bytes);
    if (try source_files.file.readPositionalAll(io, source_bytes, 0) != source_bytes.len or
        source_bytes[source_bytes.len - 1] != '\n')
        return error.SourceIdentityMismatch;
    try source_files.verify(io);
    var source_digest: [32]u8 = undefined;
    core.Sha256.hash(source_bytes[0 .. source_bytes.len - 1], &source_digest, .{});
    if (!std.mem.eql(
        u8,
        &std.fmt.bytesToHex(source_digest, .lower),
        identity.source_tree_sha256,
    )) return error.SourceIdentityMismatch;
    try verifySourceIdentityRecords(
        allocator,
        source_bytes,
        source_identity.bytes,
    );

    const expected = try expectedArtifacts(allocator, identity.variant, identity.coremark);
    defer allocator.free(expected);
    if (identity.files.count() != expected.len) return error.UnexpectedArtifactSet;
    for (expected) |artifact| {
        const expected_sha = try core.contracts.string(
            identity.files.get(artifact.name) orelse return error.UnexpectedArtifactSet,
        );
        try requireSha256(expected_sha);
        const observed = try artifactDigest(io, artifacts_path, artifact.name, artifact.mode);
        if (!std.crypto.timing_safe.eql([64]u8, observed, expected_sha[0..64].*))
            return error.ArtifactIdentityMismatch;
    }
    try verifyArtifactDirectory(io, artifacts_path, expected, published);

    const fixture = try repository.app.record(
        allocator,
        io,
        "fixture.zig",
        maximum_artifact_bytes,
        .source,
    );
    defer allocator.free(fixture.path);
    if (!std.mem.eql(u8, &fixture.sha256, try stringField(identity.fields, "fixture_source_sha256")))
        return error.TrackedSourceMismatch;
    const producer = try repository.app.record(
        allocator,
        io,
        "build-tool-prepare.zig",
        maximum_artifact_bytes,
        .source,
    );
    defer allocator.free(producer.path);
    if (!std.mem.eql(u8, &producer.sha256, try stringField(identity.fields, "prepare_source_sha256")))
        return error.TrackedSourceMismatch;
    const workload = try core.contracts.exactFields(
        identity.fields.get("workload_sources").?,
        &workload_sources,
    );
    for (workload_sources) |name| {
        const source = try repository.app.record(
            allocator,
            io,
            name,
            maximum_artifact_bytes,
            .source,
        );
        defer allocator.free(source.path);
        if (!std.mem.eql(
            u8,
            &source.sha256,
            try core.contracts.string(workload.get(name).?),
        )) return error.TrackedSourceMismatch;
    }
    const wasi_value = identity.fields.get("wasi_bridge_sha256").?;
    if (identity.coremark) {
        const wasi = try repository.app.record(
            allocator,
            io,
            "wasi.zig",
            maximum_artifact_bytes,
            .source,
        );
        defer allocator.free(wasi.path);
        if (!std.mem.eql(u8, &wasi.sha256, try core.contracts.string(wasi_value)))
            return error.TrackedSourceMismatch;
    } else if (wasi_value != .null) {
        return error.UnsupportedProducerIdentity;
    }

    try verifyCommands(allocator, identity);
    try verifyGeneratedContracts(allocator, io, identity, artifacts_path);
}

fn parseIdentity(value: std.json.Value) !IdentityView {
    const fields = try core.contracts.exactFields(value, &.{
        "schema_version",
        "scope",
        "development_only",
        "variant",
        "jit_mode",
        "wamr_revision",
        "source_tree_sha256",
        "source_identity_recipe",
        "source_tracked_diff_sha256",
        "compiler_profile",
        "zig_version",
        "runtime_options",
        "compiler_runtime_provider",
        "commands",
        "compiler_options",
        "minimal_wasi",
        "wasi_bridge_sha256",
        "fixture_source_sha256",
        "prepare_source_sha256",
        "workload_sources",
        "files",
    });
    if (try core.contracts.integer(u8, fields.get("schema_version").?) != 1)
        return error.UnsupportedProducerIdentity;
    const variant_raw = try core.contracts.string(fields.get("variant").?);
    const variant: contract.Variant = if (std.mem.eql(u8, variant_raw, "tiny"))
        .tiny
    else if (std.mem.eql(u8, variant_raw, "snapshot"))
        .snapshot
    else if (std.mem.eql(u8, variant_raw, "jit"))
        .jit
    else if (std.mem.eql(u8, variant_raw, "sample-aot"))
        .sample_aot
    else
        return error.UnsupportedProducerIdentity;
    const jit_mode = try optionalJitMode(fields.get("jit_mode").?);
    if ((variant == .jit) != (jit_mode != null))
        return error.UnsupportedProducerIdentity;
    const coremark = try boolean(fields.get("minimal_wasi").?);
    if (coremark and variant != .tiny) return error.UnsupportedProducerIdentity;
    const development = try boolean(fields.get("development_only").?);
    const source_tree_sha256 = try core.contracts.string(fields.get("source_tree_sha256").?);
    try requireSha256(source_tree_sha256);
    const files = switch (fields.get("files").?) {
        .object => |object| object,
        else => return error.ExpectedObject,
    };
    const commands = switch (fields.get("commands").?) {
        .array => |array| array,
        else => return error.ExpectedArray,
    };
    return .{
        .fields = fields,
        .variant = variant,
        .jit_mode = jit_mode,
        .coremark = coremark,
        .development = development,
        .revision = try core.contracts.string(fields.get("wamr_revision").?),
        .source_tree_sha256 = source_tree_sha256,
        .files = files,
        .commands = commands,
    };
}

fn verifySourceIdentityRecords(
    allocator: std.mem.Allocator,
    recorded_bytes: []const u8,
    current_bytes: []const u8,
) !void {
    var recorded_document = try contract.json.parse(allocator, recorded_bytes, .{
        .bytes = maximum_identity_bytes,
        .depth = 4,
        .string_bytes = 4096,
        .items = 4096,
        .tokens = 65536,
    });
    defer recorded_document.deinit();
    var current_document = try contract.json.parse(allocator, current_bytes, .{
        .bytes = maximum_identity_bytes,
        .depth = 4,
        .string_bytes = 4096,
        .items = 4096,
        .tokens = 65536,
    });
    defer current_document.deinit();
    const recorded = switch (recorded_document.value()) {
        .object => |object| object,
        else => return error.SourceIdentityMismatch,
    };
    const current = switch (current_document.value()) {
        .object => |object| object,
        else => return error.SourceIdentityMismatch,
    };
    var recorded_iterator = recorded.iterator();
    while (recorded_iterator.next()) |entry| {
        try safeRelativeSourcePath(entry.key_ptr.*);
        const actual = current.get(entry.key_ptr.*) orelse
            return error.SourceIdentityMismatch;
        try compareSourceRecords(entry.value_ptr.*, actual);
    }
    var current_iterator = current.iterator();
    while (current_iterator.next()) |entry| {
        try safeRelativeSourcePath(entry.key_ptr.*);
        try validateSourceRecord(entry.value_ptr.*);
        if (recorded.contains(entry.key_ptr.*)) continue;
        if (!std.mem.startsWith(u8, entry.key_ptr.*, "zig-pkg/"))
            return error.SourceIdentityMismatch;
    }
}

fn validateSourceRecord(value: std.json.Value) !void {
    const fields = try core.contracts.exactFields(value, &.{ "bytes", "sha256" });
    _ = try core.contracts.integer(u64, fields.get("bytes").?);
    try requireSha256(try core.contracts.string(fields.get("sha256").?));
}

fn compareSourceRecords(left: std.json.Value, right: std.json.Value) !void {
    const left_fields = try core.contracts.exactFields(left, &.{ "bytes", "sha256" });
    const right_fields = try core.contracts.exactFields(right, &.{ "bytes", "sha256" });
    if (try core.contracts.integer(u64, left_fields.get("bytes").?) !=
        try core.contracts.integer(u64, right_fields.get("bytes").?) or
        !std.mem.eql(
            u8,
            try core.contracts.string(left_fields.get("sha256").?),
            try core.contracts.string(right_fields.get("sha256").?),
        ))
        return error.SourceIdentityMismatch;
    try requireSha256(try core.contracts.string(left_fields.get("sha256").?));
}

fn safeRelativeSourcePath(path: []const u8) !void {
    if (path.len == 0 or path.len > std.fs.max_path_bytes or path[0] == '/' or
        path[path.len - 1] == '/' or std.mem.indexOfScalar(u8, path, 0) != null)
        return error.SourceIdentityMismatch;
    var components = std.mem.splitScalar(u8, path, '/');
    while (components.next()) |component| {
        if (component.len == 0 or component.len > 255 or
            std.mem.eql(u8, component, ".") or std.mem.eql(u8, component, ".."))
            return error.SourceIdentityMismatch;
    }
}

const ExpectedArtifact = struct {
    name: []const u8,
    mode: u16,
};

fn expectedArtifacts(
    allocator: std.mem.Allocator,
    variant: contract.Variant,
    coremark: bool,
) ![]ExpectedArtifact {
    var result: std.ArrayList(ExpectedArtifact) = .empty;
    errdefer result.deinit(allocator);
    try result.appendSlice(allocator, &.{
        .{ .name = "embedded.c", .mode = 0o600 },
        .{ .name = "identity.h", .mode = 0o600 },
        .{ .name = "libwamr-aot.a", .mode = 0o600 },
        .{ .name = "tiny.cwasm", .mode = 0o600 },
        .{ .name = "tiny.wasm", .mode = 0o700 },
        .{ .name = "wamr_aot.h", .mode = 0o600 },
        .{ .name = "wamrc", .mode = 0o700 },
    });
    switch (variant) {
        .tiny => {},
        .snapshot => try result.appendSlice(allocator, &.{
            .{ .name = "compute.cwasm", .mode = 0o600 },
            .{ .name = "compute.wasm", .mode = 0o600 },
            .{ .name = "memory.cwasm", .mode = 0o600 },
            .{ .name = "memory.wasm", .mode = 0o600 },
        }),
        .jit, .sample_aot => try result.appendSlice(allocator, &.{
            .{ .name = "matched.cwasm", .mode = 0o600 },
            .{ .name = "matched.wasm", .mode = 0o700 },
        }),
    }
    if (coremark) try result.appendSlice(allocator, &.{
        .{ .name = "coremark.cwasm", .mode = 0o600 },
        .{ .name = "coremark.wasm", .mode = 0o600 },
        .{ .name = "coremark-nofp.cwasm", .mode = 0o600 },
        .{ .name = "coremark-nofp.wasm", .mode = 0o600 },
    });
    std.mem.sort(ExpectedArtifact, result.items, {}, struct {
        fn less(_: void, left: ExpectedArtifact, right: ExpectedArtifact) bool {
            return std.mem.lessThan(u8, left.name, right.name);
        }
    }.less);
    return result.toOwnedSlice(allocator);
}

fn verifyArtifactDirectory(
    io: std.Io,
    artifacts_path: []const u8,
    expected: []const ExpectedArtifact,
    published: bool,
) !void {
    const directory = try contract.files.SourceDirectory.open(
        std.heap.page_allocator,
        io,
        artifacts_path,
    );
    defer directory.close(std.heap.page_allocator, io);
    var count: usize = 0;
    var iterator = directory.dir.iterate();
    while (try iterator.next(io)) |entry| {
        if (entry.kind != .file) return error.UnexpectedArtifactSet;
        if (std.mem.eql(u8, entry.name, "identity.json")) {
            if (!published) return error.UnexpectedArtifactSet;
            count += 1;
            continue;
        }
        var found = false;
        for (expected) |artifact| {
            if (std.mem.eql(u8, artifact.name, entry.name)) {
                found = true;
                break;
            }
        }
        if (!found) return error.UnexpectedArtifactSet;
        count += 1;
    }
    if (count != expected.len + @intFromBool(published))
        return error.UnexpectedArtifactSet;
}

fn verifyGeneratedContracts(
    allocator: std.mem.Allocator,
    io: std.Io,
    identity: IdentityView,
    artifacts_path: []const u8,
) !void {
    const files = identity.files;
    const header = try identityHeaderAlloc(allocator, .{
        .revision = identity.revision,
        .variant = identity.variant,
        .jit_mode = identity.jit_mode,
        .source_tree_sha256 = identity.source_tree_sha256,
        .compiler_sha256 = try fileIdentity(files, "wamrc"),
        .coremark = identity.coremark,
        .wasm_sha256 = try fileIdentity(files, "tiny.wasm"),
        .cwasm_sha256 = try fileIdentity(files, "tiny.cwasm"),
        .library_sha256 = try fileIdentity(files, "libwamr-aot.a"),
        .coremark_wasm_sha256 = if (identity.coremark) try fileIdentity(files, "coremark.wasm") else null,
        .coremark_cwasm_sha256 = if (identity.coremark) try fileIdentity(files, "coremark.cwasm") else null,
        .coremark_nofp_wasm_sha256 = if (identity.coremark) try fileIdentity(files, "coremark-nofp.wasm") else null,
        .coremark_nofp_cwasm_sha256 = if (identity.coremark) try fileIdentity(files, "coremark-nofp.cwasm") else null,
    });
    defer allocator.free(header);
    const header_path = try std.fs.path.join(allocator, &.{ artifacts_path, "identity.h" });
    defer allocator.free(header_path);
    const recorded_header = try readAbsolute(
        allocator,
        io,
        header_path,
        maximum_artifact_bytes,
    );
    defer allocator.free(recorded_header);
    if (!std.mem.eql(u8, header, recorded_header))
        return error.GeneratedContractMismatch;

    const tiny_path = try std.fs.path.join(allocator, &.{ artifacts_path, "tiny.cwasm" });
    defer allocator.free(tiny_path);
    const tiny = try readAbsolute(allocator, io, tiny_path, maximum_artifact_bytes);
    defer allocator.free(tiny);
    var coremark_bytes: ?[]u8 = null;
    defer if (coremark_bytes) |value| allocator.free(value);
    var coremark_nofp_bytes: ?[]u8 = null;
    defer if (coremark_nofp_bytes) |value| allocator.free(value);
    var payloads: [3]EmbeddedPayload = undefined;
    var count: usize = 1;
    payloads[0] = .{ .name = "wamr_fixture", .bytes = tiny };
    if (identity.coremark) {
        const coremark_path = try std.fs.path.join(
            allocator,
            &.{ artifacts_path, "coremark.cwasm" },
        );
        defer allocator.free(coremark_path);
        coremark_bytes = try readAbsolute(
            allocator,
            io,
            coremark_path,
            maximum_artifact_bytes,
        );
        const coremark_nofp_path = try std.fs.path.join(
            allocator,
            &.{ artifacts_path, "coremark-nofp.cwasm" },
        );
        defer allocator.free(coremark_nofp_path);
        coremark_nofp_bytes = try readAbsolute(
            allocator,
            io,
            coremark_nofp_path,
            maximum_artifact_bytes,
        );
        payloads[1] = .{ .name = "wamr_coremark", .bytes = coremark_bytes.? };
        payloads[2] = .{ .name = "wamr_coremark_nofp", .bytes = coremark_nofp_bytes.? };
        count = 3;
    }
    const embedded = try embeddedSourceAlloc(allocator, payloads[0..count]);
    defer allocator.free(embedded);
    const embedded_path = try std.fs.path.join(allocator, &.{ artifacts_path, "embedded.c" });
    defer allocator.free(embedded_path);
    const recorded_embedded = try readAbsolute(
        allocator,
        io,
        embedded_path,
        maximum_artifact_bytes,
    );
    defer allocator.free(recorded_embedded);
    if (!std.mem.eql(u8, embedded, recorded_embedded))
        return error.GeneratedContractMismatch;
}

fn verifyCommands(
    allocator: std.mem.Allocator,
    identity: IdentityView,
) !void {
    const app_path = "<app>";
    const work_path = "<app>/build/wamr-source";
    const artifacts_path = "<app>/build/artifacts";
    const consumer_path = "<app>/build/workload-consumer";
    if (identity.commands.items.len == 0) return error.InvalidCommandPlan;
    var index: usize = 0;
    const first = try jsonCommand(identity.commands.items[index]);
    index += 1;
    const first_argv = first.argv();
    if (first_argv.len != 2 or !std.mem.eql(u8, first_argv[1], "version") or
        !std.mem.eql(u8, first_argv[0], "<zig>") or !std.mem.eql(u8, first.cwd, app_path))
        return error.InvalidCommandPlan;
    const zig = first_argv[0];
    if (index < identity.commands.items.len) {
        const candidate = try jsonCommand(identity.commands.items[index]);
        const candidate_argv = candidate.argv();
        if (candidate_argv.len != 0 and std.mem.eql(u8, candidate_argv[0], "git")) {
            const revision_spec = try std.fmt.allocPrint(
                allocator,
                "{s}^{{commit}}",
                .{identity.revision},
            );
            defer allocator.free(revision_spec);
            try expectCommand(
                candidate,
                &.{ "git", "rev-parse", revision_spec },
                candidate.cwd,
            );
            if (!std.mem.eql(u8, candidate.cwd, "<source>"))
                return error.InvalidCommandPlan;
            index += 1;
            if (index >= identity.commands.items.len) return error.InvalidCommandPlan;
            try expectCommand(
                try jsonCommand(identity.commands.items[index]),
                &.{ "git", "archive", identity.revision },
                candidate.cwd,
            );
            index += 1;
        }
    }
    const build_path = std.fs.path.dirname(work_path) orelse return error.InvalidCommandPlan;
    const runtime = try std.fs.path.join(allocator, &.{ build_path, "runtime" });
    defer allocator.free(runtime);
    const host = try std.fs.path.join(allocator, &.{ build_path, "host" });
    defer allocator.free(host);
    try nextCommand(identity.commands.items, &index, &.{
        zig,
        "build",
        "-Dprofile=unikraft-aot",
        "-Doptimize=ReleaseSafe",
        "--prefix",
        runtime,
        "-j2",
    }, work_path);
    try nextCommand(identity.commands.items, &index, &.{
        zig,
        "build",
        "native-aot-fixture",
        "-Doptimize=ReleaseSafe",
        "-Dstrip=true",
        "--prefix",
        host,
        "-j2",
    }, work_path);
    const compiler = try std.fs.path.join(allocator, &.{ artifacts_path, "wamrc" });
    defer allocator.free(compiler);
    const profile = try std.fmt.allocPrint(
        allocator,
        "--profile={s}",
        .{contract.compiler_profile},
    );
    defer allocator.free(profile);
    if (identity.variant == .snapshot) {
        inline for (.{ "compute", "memory" }) |stem| {
            const input = try std.fmt.allocPrint(allocator, "{s}/{s}.wasm", .{ artifacts_path, stem });
            defer allocator.free(input);
            const output = try std.fmt.allocPrint(allocator, "{s}/{s}.cwasm", .{ artifacts_path, stem });
            defer allocator.free(output);
            try nextCommand(
                identity.commands.items,
                &index,
                &.{ compiler, "compile", "--target=x86_64", profile, input, "-o", output },
                app_path,
            );
        }
    } else if (identity.variant == .jit or identity.variant == .sample_aot) {
        const fixture = try std.fs.path.join(
            allocator,
            &.{ work_path, "tests", "unikraft-jit", "fixture.zig" },
        );
        defer allocator.free(fixture);
        const matched = try std.fs.path.join(allocator, &.{ artifacts_path, "matched.wasm" });
        defer allocator.free(matched);
        const emit = try std.fmt.allocPrint(allocator, "-femit-bin={s}", .{matched});
        defer allocator.free(emit);
        try nextCommand(identity.commands.items, &index, &.{
            zig,
            "build-exe",
            fixture,
            "-target",
            "wasm32-freestanding",
            "-O",
            "ReleaseSmall",
            "-fno-entry",
            "-rdynamic",
            "--stack",
            "16384",
            "--initial-memory=131072",
            "--max-memory=524288",
            emit,
        }, app_path);
        const matched_aot = try std.fs.path.join(allocator, &.{ artifacts_path, "matched.cwasm" });
        defer allocator.free(matched_aot);
        try nextCommand(
            identity.commands.items,
            &index,
            &.{ compiler, "compile", "--target=x86_64", profile, matched, "-o", matched_aot },
            app_path,
        );
    }
    const output = try std.fs.path.join(allocator, &.{ consumer_path, "out" });
    defer allocator.free(output);
    const variant_option = try std.fmt.allocPrint(
        allocator,
        "-Dvariant={s}",
        .{variantName(identity.variant)},
    );
    defer allocator.free(variant_option);
    const coremark_option = try std.fmt.allocPrint(
        allocator,
        "-Dcoremark={s}",
        .{if (identity.coremark) "true" else "false"},
    );
    defer allocator.free(coremark_option);
    try nextCommand(identity.commands.items, &index, &.{
        zig,
        "build",
        variant_option,
        coremark_option,
        "-j2",
        "--prefix",
        output,
    }, consumer_path);
    const library = try std.fs.path.join(allocator, &.{ output, "lib", "libwamr-aot.a" });
    defer allocator.free(library);
    const stripped = try std.fs.path.join(
        allocator,
        &.{ build_path, "scratch", "libwamr-aot.stripped.a" },
    );
    defer allocator.free(stripped);
    if (index >= identity.commands.items.len) return error.InvalidCommandPlan;
    const strip = try jsonCommand(identity.commands.items[index]);
    const strip_argv = strip.argv();
    if (strip_argv.len != 4 or !std.mem.eql(u8, strip_argv[0], "<objcopy>"))
        return error.InvalidCommandPlan;
    try nextCommand(identity.commands.items, &index, &.{
        strip_argv[0], "--strip-debug", library, stripped,
    }, work_path);
    const fixture = try std.fs.path.join(allocator, &.{ app_path, "fixture.zig" });
    defer allocator.free(fixture);
    const tiny = try std.fs.path.join(allocator, &.{ artifacts_path, "tiny.wasm" });
    defer allocator.free(tiny);
    const emit = try std.fmt.allocPrint(allocator, "-femit-bin={s}", .{tiny});
    defer allocator.free(emit);
    try nextCommand(identity.commands.items, &index, &.{
        zig,
        "build-exe",
        fixture,
        "-target",
        "wasm32-freestanding",
        "-O",
        "ReleaseSmall",
        "-fno-entry",
        "-rdynamic",
        "--stack",
        "16384",
        "--initial-memory=131072",
        "--max-memory=524288",
        emit,
    }, app_path);
    const tiny_aot = try std.fs.path.join(allocator, &.{ artifacts_path, "tiny.cwasm" });
    defer allocator.free(tiny_aot);
    try nextCommand(
        identity.commands.items,
        &index,
        &.{ compiler, "compile", "--target=x86_64", profile, tiny, "-o", tiny_aot },
        app_path,
    );
    if (identity.coremark) {
        inline for (.{ "coremark", "coremark-nofp" }) |stem| {
            const input = try std.fmt.allocPrint(allocator, "{s}/{s}.wasm", .{ artifacts_path, stem });
            defer allocator.free(input);
            const output_path = try std.fmt.allocPrint(
                allocator,
                "{s}/{s}.cwasm",
                .{ artifacts_path, stem },
            );
            defer allocator.free(output_path);
            try nextCommand(
                identity.commands.items,
                &index,
                &.{ compiler, "compile", "--target=x86_64", profile, input, "-o", output_path },
                app_path,
            );
        }
    }
    if (index != identity.commands.items.len) return error.InvalidCommandPlan;
}

const JsonCommand = struct {
    storage: [64][]const u8,
    len: usize,
    cwd: []const u8,

    fn argv(self: *const JsonCommand) []const []const u8 {
        return self.storage[0..self.len];
    }
};

fn jsonCommand(value: std.json.Value) !JsonCommand {
    const fields = try core.contracts.exactFields(value, &.{ "argv", "cwd" });
    const array = switch (fields.get("argv").?) {
        .array => |items| items,
        else => return error.ExpectedArray,
    };
    if (array.items.len == 0 or array.items.len > 64) return error.InvalidCommandPlan;
    var result: JsonCommand = .{
        .storage = undefined,
        .len = array.items.len,
        .cwd = try core.contracts.string(fields.get("cwd").?),
    };
    for (array.items, 0..) |argument, index|
        result.storage[index] = try core.contracts.string(argument);
    return result;
}

fn nextCommand(
    commands: []const std.json.Value,
    index: *usize,
    argv: []const []const u8,
    cwd: []const u8,
) !void {
    if (index.* >= commands.len) return error.InvalidCommandPlan;
    try expectCommand(try jsonCommand(commands[index.*]), argv, cwd);
    index.* += 1;
}

fn expectCommand(actual: JsonCommand, argv: []const []const u8, cwd: []const u8) !void {
    const actual_argv = actual.argv();
    if (actual_argv.len != argv.len or !std.mem.eql(u8, actual.cwd, cwd))
        return error.InvalidCommandPlan;
    for (actual_argv, argv) |left, right|
        if (!std.mem.eql(u8, left, right)) return error.InvalidCommandPlan;
}

fn configureBuildEnvironment(
    allocator: std.mem.Allocator,
    io: std.Io,
    build: std.Io.Dir,
    build_path: []const u8,
    scratch_path: []const u8,
    environment: *std.process.Environ.Map,
) !void {
    const scratch = try contract.files.ensurePrivateDirectory(io, build, "scratch");
    scratch.close(io);
    const state = try contract.files.ensurePrivateDirectory(io, build, "native-environment");
    defer state.close(io);
    inline for (.{
        .{ "xdg_cache", "XDG_CACHE_HOME" },
        .{ "xdg_config", "XDG_CONFIG_HOME" },
        .{ "zig_global_cache", "ZIG_GLOBAL_CACHE_DIR" },
        .{ "zig_local_cache", "ZIG_LOCAL_CACHE_DIR" },
    }) |item| {
        const directory = try contract.files.ensurePrivateDirectory(io, state, item[0]);
        directory.close(io);
        const path = try std.fs.path.join(
            allocator,
            &.{ build_path, "native-environment", item[0] },
        );
        defer allocator.free(path);
        try environment.put(item[1], path);
    }
    try environment.put("TMPDIR", scratch_path);
}

fn configureZigLibrary(
    allocator: std.mem.Allocator,
    io: std.Io,
    zig_path: []const u8,
    environment: *std.process.Environ.Map,
) !void {
    var allocated: ?[]u8 = null;
    defer if (allocated) |path| allocator.free(path);
    const selected = environment.get("ZIG_LIB_DIR") orelse selected: {
        const executable_directory = std.fs.path.dirname(zig_path) orelse
            return error.InvalidToolLayout;
        allocated = try std.fs.path.join(allocator, &.{ executable_directory, "lib" });
        break :selected allocated.?;
    };
    const directory = try contract.files.SourceDirectory.open(allocator, io, selected);
    defer directory.close(allocator, io);
    try environment.put("ZIG_LIB_DIR", directory.path);
}

fn cloneEnvironment(
    allocator: std.mem.Allocator,
    inherited: *const std.process.Environ.Map,
) !std.process.Environ.Map {
    var result = std.process.Environ.Map.init(allocator);
    errdefer result.deinit();
    var iterator = inherited.iterator();
    while (iterator.next()) |entry| try result.put(entry.key_ptr.*, entry.value_ptr.*);
    return result;
}

fn copySourceFile(
    io: std.Io,
    source: contract.files.SourceDirectory,
    relative: []const u8,
    destination: std.Io.Dir,
    name: []const u8,
    mode: u16,
) !void {
    const input = try source.openFile(io, relative, .source);
    defer input.close(io);
    try copyFile(io, input, destination, name, mode);
}

fn trackedDigest(
    allocator: std.mem.Allocator,
    io: std.Io,
    source: contract.files.SourceDirectory,
    relative: []const u8,
) ![64]u8 {
    const record = try source.record(
        allocator,
        io,
        relative,
        maximum_artifact_bytes,
        .source,
    );
    defer allocator.free(record.path);
    return record.sha256;
}

fn copyAbsoluteFile(
    allocator: std.mem.Allocator,
    io: std.Io,
    source_path: []const u8,
    destination: std.Io.Dir,
    name: []const u8,
    mode: u16,
) !void {
    _ = allocator;
    var source = try contract.files.RetainedFile.open(io, source_path, .artifact);
    defer source.close(io);
    if (source.file_snapshot.nlink != 1) return error.UnsafeFile;
    try copyFile(io, source.file, destination, name, mode);
    try source.verify(io);
}

fn copyFile(
    io: std.Io,
    input: std.Io.File,
    destination: std.Io.Dir,
    name: []const u8,
    mode: u16,
) !void {
    const before = try contract.files.snapshot(input);
    if (before.mode & linux.S.IFMT != linux.S.IFREG or before.size > maximum_artifact_bytes)
        return error.UnsafeFile;
    const output = try destination.createFile(io, name, .{
        .exclusive = true,
        .permissions = .fromMode(mode),
    });
    defer output.close(io);
    var buffer: [64 * 1024]u8 = undefined;
    var offset: u64 = 0;
    while (offset < before.size) {
        const count = try input.readPositionalAll(
            io,
            buffer[0..@min(buffer.len, before.size - offset)],
            offset,
        );
        if (count == 0) return error.FileChanged;
        try output.writePositionalAll(io, buffer[0..count], offset);
        offset += count;
    }
    if (try input.readPositionalAll(io, buffer[0..1], offset) != 0)
        return error.FileChanged;
    if (!contract.files.sameSnapshot(before, try contract.files.snapshot(input)))
        return error.FileChanged;
    try output.setLength(io, before.size);
    try output.setPermissions(io, .fromMode(mode));
    try output.sync(io);
    try requireFile(io, output, mode, before.size);
}

fn readAbsolute(
    allocator: std.mem.Allocator,
    io: std.Io,
    path: []const u8,
    maximum: u64,
) ![]u8 {
    var retained = try contract.files.RetainedFile.open(io, path, .artifact);
    defer retained.close(io);
    if (retained.file_snapshot.size > maximum or
        retained.file_snapshot.size > std.math.maxInt(usize))
        return error.FileTooLarge;
    const result = try allocator.alloc(u8, @intCast(retained.file_snapshot.size));
    errdefer allocator.free(result);
    if (try retained.file.readPositionalAll(io, result, 0) != result.len)
        return error.FileChanged;
    try retained.verify(io);
    return result;
}

fn setAbsoluteMode(io: std.Io, path: []const u8, mode: u16) !void {
    const parent = try contract.files.FileParent.open(io, path, .artifact);
    defer parent.close(io);
    const file = try parent.openFile(io);
    defer file.close(io);
    try file.setPermissions(io, .fromMode(mode));
    try file.sync(io);
    try requireFile(io, file, mode, null);
}

fn digestAbsolute(io: std.Io, path: []const u8, maximum: u64) ![64]u8 {
    var retained = try contract.files.RetainedFile.open(io, path, .artifact);
    defer retained.close(io);
    if (retained.file_snapshot.nlink != 1) return error.UnsafeFile;
    const result = try contract.files.hashStableFile(io, retained.file, maximum);
    try retained.verify(io);
    return result;
}

fn artifactDigest(
    io: std.Io,
    artifacts_path: []const u8,
    name: []const u8,
    mode: u16,
) ![64]u8 {
    var buffer: [std.fs.max_path_bytes]u8 = undefined;
    const path = try std.fmt.bufPrint(&buffer, "{s}/{s}", .{ artifacts_path, name });
    var retained = try contract.files.RetainedFile.open(io, path, .artifact);
    defer retained.close(io);
    if (retained.file_snapshot.mode & linux.S.IFMT != linux.S.IFREG or
        retained.file_snapshot.mode & 0o7777 != mode or
        retained.file_snapshot.uid != linux.geteuid() or
        retained.file_snapshot.nlink != 1)
        return error.UnsafeArtifact;
    const result = try contract.files.hashStableFile(
        io,
        retained.file,
        maximum_artifact_bytes,
    );
    try retained.verify(io);
    return result;
}

fn requireFile(
    io: std.Io,
    file: std.Io.File,
    mode: u16,
    size: ?u64,
) !void {
    const snapshot = try contract.files.snapshot(file);
    if (snapshot.mode & linux.S.IFMT != linux.S.IFREG or
        snapshot.mode & 0o7777 != mode or snapshot.uid != linux.geteuid() or
        snapshot.nlink != 1 or (size != null and snapshot.size != size.?))
        return error.UnsafeFile;
    _ = io;
}

fn requireSourceDirectoryIdentity(
    left: contract.files.SourceDirectory,
    right: contract.files.SourceDirectory,
) !void {
    if (!std.mem.eql(u8, left.path, right.path)) return error.SourceChanged;
    const left_metadata = try @import("preparation_files").metadata(.{
        .handle = left.dir.handle,
        .flags = .{ .nonblocking = false },
    });
    const right_metadata = try @import("preparation_files").metadata(.{
        .handle = right.dir.handle,
        .flags = .{ .nonblocking = false },
    });
    if (left_metadata.device != right_metadata.device or
        left_metadata.inode != right_metadata.inode or
        left_metadata.mode != right_metadata.mode or
        left_metadata.uid != right_metadata.uid)
        return error.SourceChanged;
}

fn syncDirectory(io: std.Io, directory: std.Io.Dir) !void {
    const file: std.Io.File = .{
        .handle = directory.handle,
        .flags = .{ .nonblocking = false },
    };
    try file.sync(io);
}

fn jsonFieldName(writer: *std.Io.Writer, name: []const u8, comma: bool) !void {
    if (comma) try writer.writeByte(',');
    try contract.json.writeString(writer, name);
    try writer.writeByte(':');
}

fn writeStringArray(writer: *std.Io.Writer, values: []const []const u8) !void {
    try writer.writeByte('[');
    for (values, 0..) |value, index| {
        if (index != 0) try writer.writeByte(',');
        try contract.json.writeString(writer, value);
    }
    try writer.writeByte(']');
}

fn portableAppPath(
    allocator: std.mem.Allocator,
    value: []const u8,
    app_path: []const u8,
) !?[]const u8 {
    if (!std.mem.startsWith(u8, value, app_path) or
        (value.len != app_path.len and value[app_path.len] != '/'))
        return null;
    const portable: []const u8 = try std.fmt.allocPrint(
        allocator, "<app>{s}", .{value[app_path.len..]},
    );
    return portable;
}

fn portableCommandValue(
    allocator: std.mem.Allocator,
    value: []const u8,
    app_path: []const u8,
) ![]const u8 {
    if (try portableAppPath(allocator, value, app_path)) |portable| return portable;
    if (std.mem.indexOfScalar(u8, value, '=')) |separator| {
        if (try portableAppPath(allocator, value[separator + 1 ..], app_path)) |portable|
            return std.fmt.allocPrint(allocator, "{s}={s}", .{ value[0..separator], portable });
    }
    return value;
}

fn writeCommands(
    allocator: std.mem.Allocator,
    writer: *std.Io.Writer,
    commands: []const CommandRecord,
    app_path: []const u8,
    zig_path: []const u8,
    objcopy_path: []const u8,
) !void {
    const compiler_path = try std.fs.path.join(
        allocator, &.{ app_path, "build", "artifacts", "wamrc" },
    );
    try writer.writeByte('[');
    for (commands, 0..) |command, index| {
        if (index != 0) try writer.writeByte(',');
        try writer.writeAll("{\"argv\":");
        try writer.writeByte('[');
        for (command.argv, 0..) |argument, argument_index| {
            if (argument_index != 0) try writer.writeByte(',');
            const portable = if (argument_index == 0) tool: {
                const expected = switch (command.stage) {
                    .git_revision, .git_archive => "git",
                    .runtime_strip => objcopy_path,
                    .snapshot_compute, .snapshot_memory, .matched_aot, .tiny_aot,
                    .coremark_aot, .coremark_nofp_aot => compiler_path,
                    else => zig_path,
                };
                if (!std.mem.eql(u8, argument, expected)) return error.InvalidCommandPlan;
                break :tool switch (command.stage) {
                    .git_revision, .git_archive => "git",
                    .runtime_strip => "<objcopy>",
                    .snapshot_compute, .snapshot_memory, .matched_aot, .tiny_aot,
                    .coremark_aot, .coremark_nofp_aot => "<app>/build/artifacts/wamrc",
                    else => "<zig>",
                };
            } else try portableCommandValue(allocator, argument, app_path);
            try contract.json.writeString(writer, portable);
        }
        try writer.writeByte(']');
        try writer.writeAll(",\"cwd\":");
        try contract.json.writeString(
            writer,
            if (command.stage == .git_revision or command.stage == .git_archive)
                "<source>"
            else
                try portableCommandValue(allocator, command.cwd, app_path),
        );
        try writer.writeByte('}');
    }
    try writer.writeByte(']');
}

fn commandResultAlloc(
    allocator: std.mem.Allocator,
    stage: Stage,
    argv: []const []const u8,
    cwd: []const u8,
    result: contract.process.CommandResult,
) ![]u8 {
    var raw = std.Io.Writer.Allocating.init(allocator);
    defer raw.deinit();
    try raw.writer.writeAll("{\"argv\":");
    try writeStringArray(&raw.writer, argv);
    try raw.writer.writeAll(",\"cleanup\":");
    try contract.json.writeString(&raw.writer, @tagName(result.cleanup));
    try raw.writer.print(
        ",\"cleanup_complete\":{s},\"cleanup_events\":{d},\"completed_ns\":{d}," ++
            "\"cwd\":",
        .{
            if (result.cleanup_complete) "true" else "false",
            result.cleanup_events,
            result.completed_ns,
        },
    );
    try contract.json.writeString(&raw.writer, cwd);
    try raw.writer.print(
        ",\"descendants\":{{\"adopted\":{d},\"identity_validated\":{d}," ++
            "\"limit_exceeded\":{s},\"observed\":{d},\"untracked\":{s}}}," ++
            "\"executable_stable\":{s},\"primary\":",
        .{
            result.descendants.adopted,
            result.descendants.identity_validated,
            if (result.descendants.limit_exceeded) "true" else "false",
            result.descendants.observed,
            if (result.descendants.untracked) "true" else "false",
            if (result.executable_stable) "true" else "false",
        },
    );
    try writePrimary(&raw.writer, result.primary);
    try raw.writer.print(
        ",\"primary_completed_ns\":{d},\"primary_deadline_reached\":{s}," ++
            "\"primary_events\":{d},\"reap_events\":{d},\"stage\":",
        .{
            result.primary_completed_ns,
            if (result.primary_deadline_reached) "true" else "false",
            result.primary_events,
            result.reap_events,
        },
    );
    try contract.json.writeString(&raw.writer, stage.name());
    try raw.writer.writeAll(",\"stderr_status\":");
    try contract.json.writeString(&raw.writer, @tagName(result.stderr_status));
    try raw.writer.print(",\"started_ns\":{d},\"stdout_status\":", .{result.started_ns});
    try contract.json.writeString(&raw.writer, @tagName(result.stdout_status));
    try raw.writer.print(
        ",\"cancellation_observed\":{s}}}",
        .{if (result.cancellation_observed) "true" else "false"},
    );
    const compact = try raw.toOwnedSlice();
    defer allocator.free(compact);
    var document = try contract.json.parse(allocator, compact, .{
        .bytes = maximum_identity_bytes,
        .depth = 16,
        .string_bytes = 64 * 1024,
        .items = 1024,
        .tokens = 8192,
    });
    defer document.deinit();
    return contract.json.valueAlloc(allocator, document.value(), .pretty);
}

fn writePrimary(writer: *std.Io.Writer, primary: contract.process.CommandPrimary) !void {
    try writer.writeByte('{');
    switch (primary) {
        .exited => |code| try writer.print("\"exited\":{d}", .{code}),
        .signal => |signal| try writer.print("\"signal\":{d}", .{@intFromEnum(signal)}),
        .unknown => |status| try writer.print("\"unknown\":{d}", .{status}),
        else => try contract.json.writeString(writer, @tagName(primary)),
    }
    try writer.writeByte('}');
}

fn symbol(name: []const u8) !void {
    if (name.len == 0) return error.InvalidSymbol;
    for (name, 0..) |byte, index| {
        if (std.ascii.isAlphabetic(byte) or byte == '_' or
            (index != 0 and std.ascii.isDigit(byte))) continue;
        return error.InvalidSymbol;
    }
}

fn stringField(fields: std.json.ObjectMap, name: []const u8) ![]const u8 {
    return core.contracts.string(fields.get(name) orelse return error.MissingField);
}

fn boolean(value: std.json.Value) !bool {
    return switch (value) {
        .bool => |result| result,
        else => error.ExpectedBoolean,
    };
}

fn optionalJitMode(value: std.json.Value) !?contract.JitMode {
    return switch (value) {
        .null => null,
        .string => |raw| if (std.mem.eql(u8, raw, "fast"))
            .fast
        else if (std.mem.eql(u8, raw, "full"))
            .full
        else
            return error.UnsupportedProducerIdentity,
        else => error.ExpectedString,
    };
}

fn expectStringArray(value: std.json.Value, expected: []const []const u8) !void {
    const array = switch (value) {
        .array => |items| items,
        else => return error.ExpectedArray,
    };
    if (array.items.len != expected.len) return error.UnsupportedProducerIdentity;
    for (array.items, expected) |item, wanted|
        if (!std.mem.eql(u8, try core.contracts.string(item), wanted))
            return error.UnsupportedProducerIdentity;
}

fn requireSha256(value: []const u8) !void {
    _ = try core.contracts.parseSha256(value);
}

fn fileIdentity(files: std.json.ObjectMap, name: []const u8) ![]const u8 {
    const value = try core.contracts.string(
        files.get(name) orelse return error.UnexpectedArtifactSet,
    );
    try requireSha256(value);
    return value;
}

fn commandFailure(stage: Stage) anyerror {
    return switch (stage) {
        .zig_version => error.ZigVersionCommandFailed,
        .git_revision => error.GitRevisionCommandFailed,
        .git_archive => error.GitArchiveCommandFailed,
        .runtime_build => error.RuntimeBuildCommandFailed,
        .compiler_build => error.CompilerBuildCommandFailed,
        .runtime_strip => error.RuntimeStripCommandFailed,
        .snapshot_compute => error.SnapshotComputeCommandFailed,
        .snapshot_memory => error.SnapshotMemoryCommandFailed,
        .matched_wasm => error.MatchedWasmCommandFailed,
        .matched_aot => error.MatchedAotCommandFailed,
        .workload_build => error.WorkloadBuildCommandFailed,
        .tiny_wasm => error.TinyWasmCommandFailed,
        .tiny_aot => error.TinyAotCommandFailed,
        .coremark_aot => error.CoremarkCommandFailed,
        .coremark_nofp_aot => error.CoremarkNofpCommandFailed,
    };
}
