// SPDX-License-Identifier: BSD-3-Clause
const std = @import("std");
const contract = @import("build-tool-contract.zig");

pub const historical_comment =
    "/* Generated by prepare.py from matching trusted native bytes. */\n";

pub const EmbeddedPayload = struct {
    name: []const u8,
    bytes: []const u8,
};

pub fn embeddedSourceAlloc(
    allocator: std.mem.Allocator,
    payloads: []const EmbeddedPayload,
) ![]u8 {
    var output = std.Io.Writer.Allocating.init(allocator);
    defer output.deinit();
    try output.writer.writeAll(historical_comment);
    try output.writer.writeAll("#include <stddef.h>\n");
    for (payloads) |payload| try writeEmbedded(&output.writer, payload.name, payload.bytes);
    return output.toOwnedSlice();
}

pub fn writeEmbedded(
    writer: *std.Io.Writer,
    name: []const u8,
    payload: []const u8,
) !void {
    try symbol(name);
    try writer.print("const unsigned char {s}[] = {{\n", .{name});
    var offset: usize = 0;
    while (offset < payload.len) {
        if (offset != 0) try writer.writeAll(",\n");
        const end = @min(payload.len, offset + 16);
        for (payload[offset..end], 0..) |byte, index| {
            if (index != 0) try writer.writeByte(',');
            try writer.print("0x{x:0>2}", .{byte});
        }
        offset = end;
    }
    try writer.print("\n}};\nconst size_t {s}_size = sizeof({s});\n", .{ name, name });
}

pub const Header = struct {
    revision: []const u8,
    variant: contract.Variant,
    jit_mode: ?contract.JitMode,
    source_tree_sha256: []const u8,
    compiler_sha256: []const u8,
    coremark: bool,
    wasm_sha256: []const u8,
    cwasm_sha256: []const u8,
    library_sha256: []const u8,
    coremark_wasm_sha256: ?[]const u8 = null,
    coremark_cwasm_sha256: ?[]const u8 = null,
    coremark_nofp_wasm_sha256: ?[]const u8 = null,
    coremark_nofp_cwasm_sha256: ?[]const u8 = null,
};

pub fn identityHeaderAlloc(allocator: std.mem.Allocator, header: Header) ![]u8 {
    var output = std.Io.Writer.Allocating.init(allocator);
    defer output.deinit();
    try output.writer.print(
        "#define WAMR_REVISION \"{s}\"\n" ++
            "#define WAMR_APP_VARIANT {d}\n" ++
            "#define WAMR_JIT_BOOT_MODE {d}\n" ++
            "#define WAMR_SOURCE_TREE_SHA256 \"{s}\"\n" ++
            "#define WAMR_COMPILER_SHA256 \"{s}\"\n" ++
            "#define WAMR_HAS_COREMARK {d}\n" ++
            "#define WAMR_WASM_SHA256 \"{s}\"\n" ++
            "#define WAMR_CWASM_SHA256 \"{s}\"\n" ++
            "#define WAMR_LIBRARY_SHA256 \"{s}\"\n",
        .{
            header.revision,
            @intFromEnum(header.variant),
            if (header.jit_mode) |mode| @intFromEnum(mode) + 1 else 0,
            header.source_tree_sha256,
            header.compiler_sha256,
            @intFromBool(header.coremark),
            header.wasm_sha256,
            header.cwasm_sha256,
            header.library_sha256,
        },
    );
    if (header.coremark) {
        try output.writer.print(
            "#define WAMR_COREMARK_WASM_SHA256 \"{s}\"\n" ++
                "#define WAMR_COREMARK_CWASM_SHA256 \"{s}\"\n" ++
                "#define WAMR_COREMARK_NOFP_WASM_SHA256 \"{s}\"\n" ++
                "#define WAMR_COREMARK_NOFP_CWASM_SHA256 \"{s}\"\n",
            .{
                header.coremark_wasm_sha256 orelse return error.MissingCoremarkIdentity,
                header.coremark_cwasm_sha256 orelse return error.MissingCoremarkIdentity,
                header.coremark_nofp_wasm_sha256 orelse return error.MissingCoremarkIdentity,
                header.coremark_nofp_cwasm_sha256 orelse return error.MissingCoremarkIdentity,
            },
        );
    }
    return output.toOwnedSlice();
}

fn symbol(name: []const u8) !void {
    if (name.len == 0) return error.InvalidSymbol;
    for (name, 0..) |byte, index| {
        if (std.ascii.isAlphabetic(byte) or byte == '_' or
            (index != 0 and std.ascii.isDigit(byte))) continue;
        return error.InvalidSymbol;
    }
}
